export const screenNames = {
  Drawer: 'Drawer',
  BottomTab: 'BottomTab',
  Login: 'Login',
  Feed: 'Feed',
  Profile: 'Profile',
  Matrimony:'Matrimony',
  FamilyTree:'Family Tree',
  Setting:'Setting',
  RegistrationForm:'Registration Form',
  Post: 'Post',
  Feed1:"Feed1",
  Feed2:"Feed2",
  Feed3:"Feed3",
  Feed4:"Feed4",
  Feed5:"Feed5",
};
